//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManxBirdLifeAppWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBL_SightDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MBL_SightDetails()
        {
            this.MBL_SpeciesSightingDetails = new HashSet<MBL_SpeciesSightingDetails>();
        }
    
        public int SightDetailsID { get; set; }
        public int SightReportUserID { get; set; }
        public int LocationID { get; set; }
        public string GridReference { get; set; }
        public System.DateTime SightDateTime { get; set; }
        public System.DateTime SubmitDateTime { get; set; }
    
        public virtual LocationLookup LocationLookup { get; set; }
        public virtual MBL_SightReportUser MBL_SightReportUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MBL_SpeciesSightingDetails> MBL_SpeciesSightingDetails { get; set; }
    }
}
