//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManxBirdLifeAppWebApi.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManxBirdLifeAppEntities : DbContext
    {
        public ManxBirdLifeAppEntities()
            : base("name=ManxBirdLifeAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LocationLookup> LocationLookups { get; set; }
        public virtual DbSet<MBL_SightDetails> MBL_SightDetails { get; set; }
        public virtual DbSet<MBL_SightReportUser> MBL_SightReportUser { get; set; }
        public virtual DbSet<MBL_SpeciesSightingDetails> MBL_SpeciesSightingDetails { get; set; }
        public virtual DbSet<MBL_SpeciesSightingUploadFile> MBL_SpeciesSightingUploadFile { get; set; }
        public virtual DbSet<SpeciesLookup> SpeciesLookups { get; set; }
    }
}
