//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManxBirdLifeAppWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeciesLookup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpeciesLookup()
        {
            this.MBL_SpeciesSightingDetails = new HashSet<MBL_SpeciesSightingDetails>();
        }
    
        public int SpeciesID { get; set; }
        public int TaxaLevel { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> SensitiveStartDate { get; set; }
        public Nullable<System.DateTime> SensitiveEndDate { get; set; }
        public Nullable<bool> boolManuallyAddedRecord { get; set; }
        public Nullable<bool> boolApprovedByAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MBL_SpeciesSightingDetails> MBL_SpeciesSightingDetails { get; set; }
    }
}
